import React from "react";
import "./FAQ.css";
import icon11 from "../assets/icon11.svg";
import icon12 from "../assets/icon12.png";
import icon13 from "../assets/icon13.svg";
import icon14 from "../assets/icon14.svg";

function FAQ() {
  return (
    <>
      <section>
        <div className="pic">
          <div className="major-div">
            <h1 className="FAQ-h1"> FAQ </h1>{" "}
            <div className="All-FAQ">
              <ul className="ul-design">
                <li className="li-design">
                  <h3 className="li-design-1"> Is coverai.pro accurate ? </h3>{" "}
                  <p className="p-design-1">
                    The cover letter is generated by Artificial intelligence,
                    largely fed by the answers to the questions you give.The
                    most accurate are your answers, the most accurate is the
                    letter.We recommend in all circumstances to always review
                    the cover letter before sending it.{" "}
                  </p>{" "}
                </li>{" "}
                <li className="li-design">
                  <h3 className="li-design-1"> Is my information secure ? </h3>{" "}
                  <p className="p-design-1">
                    Your anonymity is important to us.Your personal information
                    and identity is not shared with anyone.{" "}
                  </p>{" "}
                </li>{" "}
                <li className="li-design">
                  <h3 className="li-design-1"> Is my information secure ? </h3>{" "}
                  <p className="p-design-1">
                    Your anonymity is important to us.Your personal information
                    and identity is not shared with anyone.{" "}
                  </p>{" "}
                </li>{" "}
                <li className="li-design">
                  <h3 className="li-design-1"> Is my information secure ? </h3>{" "}
                  <p className="p-design-1">
                    Your anonymity is important to us.Your personal information
                    and identity is not shared with anyone.{" "}
                  </p>{" "}
                </li>{" "}
                <li className="li-design">
                  <h3 className="li-design-1"> Is my information secure ? </h3>{" "}
                  <p className="p-design-1">
                    Your anonymity is important to us.Your personal information
                    and identity is not shared with anyone.{" "}
                  </p>{" "}
                </li>{" "}
              </ul>{" "}
            </div>{" "}
          </div>{" "}
        </div>{" "}
      </section>{" "}
    </>
  );
}

export default FAQ;
